### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError:

### ISSUE THREAD

**Issue by Yangleyang** [tencent-ailab/hifi3dface#32]
hello when i run run_opt_rgbd.sh，
In the fourth step, the following problem occurred, can you help me solve it?

---- step4 start -----
running base: /home/lab105/data1/yly/hifi3dface-main/test_data/RGBD/test1//prefit/
End of rasterization
End of rasterization
End of rasterization
End of rasterization
End of rasterization
End of rasterization
uv_batch:  (1, 512, 512, 3)
uv_rgb:  (1, 512, 512, 3)
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1]
2022-02-09 14:52:43.335231: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2022-02-09 14:52:43.337366: I tensorflow/core/common_runtime/process_util.cc:63] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2022-02-09 14:52:46.406315: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: flat indices[23830, :] = [0, -1, -1] does not index into param (shape: [1,640,480,3]).
2022-02-09 14:52:46.421838: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: flat indices[262140, :] = [0, -1, -1] does not index into param (shape: [1,640,480,3]).
2022-02-09 14:52:46.447786: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at gather_nd_op.cc:50 : Invalid argument: flat indices[238309, :] = [0, -1, -1] does not index into param (shape: [1,640,480,3]).
Traceback (most recent call last):
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[23830, :] = [0, -1, -1] does not index into param (shape: [1,640,480,3]).
         [[Node: GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](truediv, Reshape_9)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "step4A_prefit_Albedo_Global.py", line 308, in <module>
    tf.app.run(main)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "step4A_prefit_Albedo_Global.py", line 230, in main
    proj_xyz_right_batch: pro_xyz_list[2][np.newaxis,...] ,
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[23830, :] = [0, -1, -1] does not index into param (shape: [1,640,480,3]).
         [[Node: GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](truediv, Reshape_9)]]

Caused by op 'GatherNd_1', defined at:
  File "step4A_prefit_Albedo_Global.py", line 308, in <module>
    tf.app.run(main)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "step4A_prefit_Albedo_Global.py", line 146, in main
    512)
  File "../../utils/unwrap_utils.py", line 209, in unwrap_img_into_uv
    uv_size,
  File "../../utils/unwrap_utils.py", line 68, in warp_img_to_uv
    uv_map = tf.gather_nd(img_attrs, batch_uv_pos)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2975, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/lab105/anaconda3/envs/hifi3d/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): flat indices[23830, :] = [0, -1, -1] does not index into param (shape: [1,640,480,3]).
         [[Node: GatherNd_1 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](truediv, Reshape_9)]]

**Comment by ihongxx** [comment]
I have the same problem, have you solved the this problem ?

**Comment by ZhenyanSun** [comment]
> 

have you solved it？

**Comment by Jidi123** [comment]
i have fixed the issues. If you need help pls contact me.  Noted this is not for free.
