### ISSUE TITLE
sh run_opt_rgb.sh error

### ISSUE THREAD

**Issue by stone100010** [tencent-ailab/hifi3dface#5]
大神你好，我使用的docker配置的tensorflow1.15.0环境，requirements.txt已经根据当前环境安装完成，即包版本存在个别更改，但是在运行“sh run_opt_rgb.sh ”时候报了下面的错误，恳请大神帮忙解答一下，或者提示我是否有必要完全按照您tensorflow-gpu1.8.0去配置我本地的环境。
Traceback (most recent call last):
  File "run_RGB_opt.py", line 43, in <module>
    from utils.render_img import render_img_in_different_pose
  File "../../utils/render_img.py", line 40, in <module>
    from .project import Projector, Shader
  File "../../utils/project.py", line 39, in <module>
    from third_party.rasterize_triangles import rasterize_clip_space
  File "../../third_party/rasterize_triangles.py", line 31, in <module>
    os.path.join("/hifi3dface/third_party", "kernels/rasterize_triangles_kernel.so")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /hifi3dface/third_party/kernels/rasterize_triangles_kernel.so: invalid ELF header
RGB opt failed
期待您的回复，感谢您！

**Comment by zw20045500** [comment]
请问run_opt_rgb.sh 可以执行吗？
