### ISSUE TITLE
Error  - self._traceback = tf_stack.extract_stack_for_node(self._c_op)

### ISSUE THREAD

**Issue by MehmetOKUYAR** [tencent-ailab/hifi3dface#51]
~~~
step: 0
time:7.65780782699585
step: 1
time:7.757291316986084
step: 2
time:0.8211584091186523
step: 3
time:0.8079657554626465
step: 4
time:0.8135664463043213
step: 5
time:0.8051269054412842
step: 6
time:0.831916332244873
step: 7
time:0.7899782657623291
step: 8
time:0.8506298065185547
step: 9
time:0.7943072319030762
step: 10
time:0.8280911445617676
step: 11
time:0.850764274597168
step: 12
time:0.8188886642456055
step: 13
time:0.8308606147766113
Traceback (most recent call last):
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1359, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1451, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: input image must be of non-zero size
	 [[{{node resize/ResizeBilinear}}]]
  (1) Invalid argument: input image must be of non-zero size
	 [[{{node resize/ResizeBilinear}}]]
	 [[real_1/clip_by_value_4-0-0-TransposeNCHWToNHWC-LayoutOptimizer/_2477]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ai-ws/Desktop/hifi3dface/optimization/rgb/run_RGB_opt.py", line 392, in <module>
    app.run(RGB_opt)
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ai-ws/Desktop/hifi3dface/optimization/rgb/run_RGB_opt.py", line 272, in RGB_opt
    out_summary = sess.run(summary_op)
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1368, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/ai-ws/Desktop/hifi3dface/venv39/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: input image must be of non-zero size
	 [[node resize/ResizeBilinear (defined at /optimization/rgb/../../utils/crop_render_img.py:109) ]]
  (1) Invalid argument: input image must be of non-zero size
	 [[node resize/ResizeBilinear (defined at /optimization/rgb/../../utils/crop_render_img.py:109) ]]
	 [[real_1/clip_by_value_4-0-0-TransposeNCHWToNHWC-LayoutOptimizer/_2477]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node resize/ResizeBilinear:
 strided_slice_92 (defined at /optimization/rgb/../../utils/crop_render_img.py:108)

Input Source operations connected to node resize/ResizeBilinear:
 strided_slice_92 (defined at /optimization/rgb/../../utils/crop_render_img.py:108)

Original stack trace for 'resize/ResizeBilinear':
  File "/optimization/rgb/run_RGB_opt.py", line 392, in <module>
    app.run(RGB_opt)
  File "/venv39/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/venv39/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/optimization/rgb/run_RGB_opt.py", line 246, in RGB_opt
    out_list = build_RGB_opt_graph(var_list, basis3dmm, imageH, imageW)
  File "/optimization/rgb/run_RGB_opt.py", line 159, in build_RGB_opt_graph
    tot_loss, tot_loss_illum = compute_loss(
  File "/optimization/rgb/../../utils/compute_loss.py", line 174, in compute_loss
    render_image_fake_M = crop_render_img.tf_crop_by_landmark(
  File "/optimization/rgb/../../utils/crop_render_img.py", line 128, in tf_crop_by_landmark
    image_crop = crop_render_img._tf_crop_resize_face_by_bbox(
  File "/optimization/rgb/../../utils/crop_render_img.py", line 109, in _tf_crop_resize_face_by_bbox
    image_crop = tf.image.resize(image_pad, (300, 300))
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1717, in resize_images_v2
    return _resize_images_common(
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1450, in _resize_images_common
    images = resizer_fn(images, size)
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1699, in resize_fn
    return gen_image_ops.resize_bilinear(
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/ops/gen_image_ops.py", line 3683, in resize_bilinear
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3557, in _create_op_internal
    ret = Operation(
  File "/venv39/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

RGB opt failed
~~~
train starting but ı have error like this. Do you know any idea.
tensorflow --->  2.6.2
cuda ---> 11.7
gpu ---> quadro A5500 24GB

**Comment by MehmetOKUYAR** [comment]
its working sometimes very well , sometimes give this error. ı dont understand why
